import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "./components/common/Sidebar/Sidebar";

// Load custom fonts from the public folder
const geistSans = localFont({
  src: "/fonts/GeistVF.woff", // Path to the public folder
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "/fonts/GeistMonoVF.woff", // Path to the public folder
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* You can put any global metadata here */}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex justify-center items-center ">
          {/* First Column (20% width) */}
          <div className="w-[20%] border-2  ">
            <Sidebar />
          </div>

          {/* Second Column (80% width) */}
          <div className="w-[80%] border-2  ">
            {/* Content goes here */}
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. In inventore quis magnam unde accusantium nam iure rem, odio et officia.</p>
          </div>
        </div>

        {/* Render children passed to RootLayout */}
        <div className="flex-1">
          {children}
        </div>
      </body>
    </html>
  );
}
